

services:
  postgres:
    image: postgres:15
    container_name: dwh_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
volumes:
  pgdata:
